// Code generated by MockGen. DO NOT EDIT.
// Source: campaign/interfaces/usecase.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/tokopedia/go-test/domain/campaign/model"
)

// MockCampaignUsecase is a mock of CampaignUsecase interface.
type MockCampaignUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignUsecaseMockRecorder
}

// MockCampaignUsecaseMockRecorder is the mock recorder for MockCampaignUsecase.
type MockCampaignUsecaseMockRecorder struct {
	mock *MockCampaignUsecase
}

// NewMockCampaignUsecase creates a new mock instance.
func NewMockCampaignUsecase(ctrl *gomock.Controller) *MockCampaignUsecase {
	mock := &MockCampaignUsecase{ctrl: ctrl}
	mock.recorder = &MockCampaignUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignUsecase) EXPECT() *MockCampaignUsecaseMockRecorder {
	return m.recorder
}

// CreateCampaign mocks base method.
func (m *MockCampaignUsecase) CreateCampaign(param model.CampaignUcCreateCampaignParam) (model.CampaignUcCreateCampaignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCampaign", param)
	ret0, _ := ret[0].(model.CampaignUcCreateCampaignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCampaign indicates an expected call of CreateCampaign.
func (mr *MockCampaignUsecaseMockRecorder) CreateCampaign(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCampaign", reflect.TypeOf((*MockCampaignUsecase)(nil).CreateCampaign), param)
}

// SendCampaign mocks base method.
func (m *MockCampaignUsecase) SendCampaign(param model.CampaignUcSendCampaignParam) (model.CampaignUcSendCampaignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCampaign", param)
	ret0, _ := ret[0].(model.CampaignUcSendCampaignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCampaign indicates an expected call of SendCampaign.
func (mr *MockCampaignUsecaseMockRecorder) SendCampaign(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCampaign", reflect.TypeOf((*MockCampaignUsecase)(nil).SendCampaign), param)
}
